### PR TITLE
Strip username from request

### PR DESCRIPTION
**Pull request by andrewshkovskii**

### CODE REVIEW

**Comment by andrewshkovskii** [comment]
[H1: перебор паролей](https://trello.com/c/UPxo0GvW/248-h1-%D0%BF%D0%B5%D1%80%D0%B5%D0%B1%D0%BE%D1%80-%D0%BF%D0%B0%D1%80%D0%BE%D0%BB%D0%B5%D0%B9)

**Comment by dmitry-mukhin** [comment]
This is a horrible PR.
Please separate merging upstream and adding new functionality to two.

**Comment by andrewshkovskii** [comment]
@dmitry-mukhin Done

**Review by dmitry-mukhin — CHANGES_REQUESTED** [review]
can you try to prepare this so we could send nice PR upstream?

tests/changelog

The issue could be relevant for all other defender users.

**Comment by andrewshkovskii** [comment]
@dmitry-mukhin 
I created PR in upstream repo: https://github.com/kencochrane/django-defender/pull/122

But note, that PR contains some complexity due need of testing new feature. Just read comments.

**Comment by andrewshkovskii** [comment]
@dmitry-mukhin 
I created PR in upstream repo: https://github.com/kencochrane/django-defender/pull/122

But note, that PR contains some complexity due to the need of testing a new feature. Just read comments.

**Comment by homm** [comment]
Мамочки, такое количество изменений (#133) для такой фигулинки (

**Comment by dmitry-mukhin** [comment]
122?

**Comment by andrewshkovskii** [comment]
@homm Well, you can look at the last comment in the upstream PR. Some of the changes can be discarded and diff will be much smaller.

**Comment by andrewshkovskii** [comment]
Closed prior #3

**Pull request closed without merging**
